// fetchGame
export const FETCH_GAMES_BEGIN = "FETCH_GAMES_BEGIN";
export const FETCH_GAMES_SUCCESS = "FETCH_GAMES_SUCCESS";
export const FETCH_GAMES_FAILURE = "FETCH_GAMES_FAILURE";
// saveGame
export const SAVE_GAME_BEGIN = "SAVE_GAME_BEGIN";
export const SAVE_GAME_SUCCESS = "SAVE_GAME_SUCCESS";
export const SAVE_GAME_FAILURE = "SAVE_GAME_FAILURE";
export const OPEN_SAVING_MODAL = "OPEN_SAVING_MODAL";
export const CLOSE_SAVING_MODAL = "CLOSE_SAVING_MODAL";
export const REMOVE_LOCK = "REMOVE_LOCK";
// deleteGame
export const DELETE_GAME_BEGIN = "DELETE_GAME_BEGIN";
export const DELETE_GAME_SUCCESS = "DELETE_GAME_SUCCESS";
export const DELETE_GAME_FAILURE = "DELETE_GAME_FAILURE";
export const OPEN_DELETION_MODAL = "OPEN_DELETION_MODAL";
export const CLOSE_DELETION_MODAL = "CLOSE_DELETION_MODAL";
// board
export const DELETE_GAME = "DELETE_GAME";
export const CLICK_SQUARE = "CLICK_SQUARE";
export const START_GAME = "START_GAME";
export const RESTART_GAME = "RESTART_GAME";
export const FINISH_GAME = "FINISH_GAME";
// activeGame
export const SELECT_KEY = "SELECT_KEY";
