// saving
export const SAVE_GAME_SUCCESS = "SAVE_GAME_SUCCESS";
export const SAVE_GAME_FAILURE = "SAVE_GAME_FAILURE";
// fetching
export const FETCH_GAMES_SUCCESS = "FETCH_GAMES_SUCCESS";
export const FETCH_GAMES_FAILURE = "FETCH_GAMES_FAILURE";
// deleting
export const DELETE_GAME_SUCCESS = "DELETE_GAME_SUCCESS";
export const DELETE_GAME_FAILURE = "DELETE_GAME_FAILURE";
// gameplay info
export const START_GAME_INFO = "START_GAME_INFO";
export const FINISH_GAME_INFO = "FINISH_GAME_INFO";
export const RESTART_GAME_INFO = "RESTART_GAME_INFO";
export const ITEM_ALREADY_PLACED = "ITEM_ALREADY_PLACED";
